#客户端配置
client:
  log-path: ./logs
top:
  zenyoung:
    netty:
      client:
        host: 127.0.0.1
        port: 5610
        log-level: debug
        heartbeat-interval: PT60S
#日志级别
logging:
  level:
    root: INFO
    io.netty: DEBUG
    top.zenyoung.proxy: DEBUG